"""The domain layer: commands, events, and the decider that relates them.

Depends on nothing but the event-sourcing primitives and pydantic. No
langchain, no deepagents, no SQLite, no environment. Everything above may
import from here; nothing here imports from above.
"""

from research_team.domain.auto_research import (
    AutoResearchRun,
    AutoRunState,
    Budget,
    StartRun,
)
from research_team.domain.commands import (
    ChangeAutonomy,
    CompactConversation,
    CompleteTurn,
    DeleteFile,
    EditFile,
    FailTurn,
    RecordAssistantMessage,
    RecordForkSource,
    RecordToolDecision,
    RecordToolResult,
    SendUserMessage,
    SessionCommand,
    StartSession,
    WriteFile,
)
from research_team.domain.corpus import (
    Corpus,
    CorpusState,
    DocumentRecord,
    DropSourceDocument,
    SourceDocumentDropped,
    SourceDocumentStored,
    StoreSourceDocument,
)
from research_team.domain.events import (
    SESSION_EVENTS,
    AssistantMessageAdded,
    AutonomyChanged,
    ConversationCompacted,
    FileDeleted,
    FileEdited,
    FileWritten,
    SessionForkedFrom,
    SessionStarted,
    ToolCallDecided,
    ToolResultRecorded,
    TurnCompleted,
    TurnFailed,
    UserMessageSent,
)
from research_team.domain.learner import (
    ChecklistProgressRecorded,
    ItemAnswered,
    ItemCompleted,
    ItemRecord,
    LearnerProgress,
    LearnerProgressState,
    RecordAttempt,
    RecordChecklistState,
)
from research_team.domain.project import (
    AdvanceStage,
    AdvanceTip,
    CreateProject,
    DeleteProject,
    JoinProject,
    Project,
    ProjectCreated,
    ProjectDeleted,
    ProjectState,
    ProjectTipAdvanced,
    SelectWorkflow,
    SessionJoinedProject,
    StageAdvanced,
    WorkflowSelected,
    current_stage_of,
)
from research_team.domain.session import (
    CodingSession,
    SessionState,
    decide,
    evolve,
    initial_state,
)

__all__ = [
    "SESSION_EVENTS",
    "AdvanceStage",
    "AdvanceTip",
    "AssistantMessageAdded",
    "AutoResearchRun",
    "AutoRunState",
    "AutonomyChanged",
    "Budget",
    "ChangeAutonomy",
    "ChecklistProgressRecorded",
    "CodingSession",
    "CompactConversation",
    "CompleteTurn",
    "ConversationCompacted",
    "Corpus",
    "CorpusState",
    "CreateProject",
    "DeleteFile",
    "DeleteProject",
    "DocumentRecord",
    "DropSourceDocument",
    "EditFile",
    "FailTurn",
    "FileDeleted",
    "FileEdited",
    "FileWritten",
    "ItemAnswered",
    "ItemCompleted",
    "ItemRecord",
    "JoinProject",
    "LearnerProgress",
    "LearnerProgressState",
    "Project",
    "ProjectCreated",
    "ProjectDeleted",
    "ProjectState",
    "ProjectTipAdvanced",
    "RecordAssistantMessage",
    "RecordAttempt",
    "RecordChecklistState",
    "RecordForkSource",
    "RecordToolDecision",
    "RecordToolResult",
    "SelectWorkflow",
    "SendUserMessage",
    "SessionCommand",
    "SessionForkedFrom",
    "SessionJoinedProject",
    "SessionStarted",
    "SessionState",
    "SourceDocumentDropped",
    "SourceDocumentStored",
    "StageAdvanced",
    "StartRun",
    "StartSession",
    "StoreSourceDocument",
    "ToolCallDecided",
    "ToolResultRecorded",
    "TurnCompleted",
    "TurnFailed",
    "UserMessageSent",
    "WorkflowSelected",
    "WriteFile",
    "current_stage_of",
    "decide",
    "evolve",
    "initial_state",
]
