"""The override table, behind `SettingsStorePort`.

**A store with no projection, and the reason is not laziness.** Every other
read model here is a fold of the log, which is right for anything whose history
is the point. A setting is not that: what a project's chat model *is* right now
is the whole question, and replaying "someone set it to X, then Y, then X" adds
nothing a reader needs. `EntityDefinitionStore` is the precedent -- its
docstring makes the same argument -- and this store still owns reconciling its
own schema, which is the part every caller needs and none should duplicate.

What that costs, stated plainly: there is no audit trail of settings changes.
Who changed a project's extraction chunk size and when is not answerable from
this table beyond `updated_at`, and a `SettingChanged` event is the thing to add
when it becomes a question anyone asks. It is deferred rather than forgotten --
the master plan's tenancy work (W-B) is where "who" starts existing at all, and
an audit event written before there is an identity to attribute it to would
record `None` for the only field anybody would query.

The table lives in the same database as everything else (`AGENT_DB`), which is
why `AGENT_DB` itself stays environment-only: a setting whose value decides
which database holds the settings cannot be read from that database.
"""

import asyncio
from collections.abc import Iterable
from datetime import UTC, datetime
from uuid import UUID, uuid5

import aiosqlite
from eventsource import ReadModel
from eventsource.adapters.sqlite.readmodels import SQLiteReadModelRepository
from eventsource.ports.readmodels import Filter, Query, ReadModelRepository

from research_team.application.effective import SettingsRevision
from research_team.domain.settings import Override, Scope, ScopeRef
from research_team.infrastructure.persistence.read_models import apply_schema

SETTINGS_NAMESPACE = UUID("2b6f9c14-7d3a-5e08-b192-4c7a0e5d38f6")


class SettingOverrideRow(ReadModel):
    """One override. The triple `(scope, scope_id, setting_key)` is the identity.

    `setting_key` rather than `key`: `key` is a word SQLite tolerates and a
    reader does not -- a column called `key` in a table of keys and values says
    nothing about which of the two it is, and the ambiguity survives into every
    query anyone writes against it by hand.

    `value` holds the serialised form for an ordinary setting and the
    ciphertext for a secret. One column rather than two, because a second
    column would be a second place for the answer to "is this encrypted" to
    live, free to disagree with `SettingSpec.secret`, which is the only
    authority on it.
    """

    __table_name__ = "setting_overrides"

    scope: str
    scope_id: str
    setting_key: str
    value: str
    updated_at: datetime
    """A `datetime`, not the ISO string it looks like in the API.

    Declared as `str` first, which round-trips wrong: the SQLite adapter gives
    an `_at` column a TIMESTAMP affinity and hands the value back as a
    `datetime`, so every read failed pydantic validation on a row this class
    had itself written. The API's string is produced at the boundary instead.
    """

    @staticmethod
    def row_id(scope: Scope, scope_id: str, key: str) -> UUID:
        """The id for a triple. Derived rather than random for the reason every
        other `row_id` here is: a second write to the same setting has to
        replace the first, and an autogenerated id would accumulate a row per
        edit that only the newest of which anyone would ever read."""
        return uuid5(SETTINGS_NAMESPACE, f"{scope.value}:{scope_id}:{key}")


class SettingsStore:
    """`SettingsStorePort` over SQLite. Knows scopes, keys and strings.

    Deliberately ignorant of resolution order, typing, validation and secrecy
    -- all four are `SettingsResolver`'s, so a second store cannot quietly
    disagree with the first about what `project` beats.

    **Opens on first use, not at construction, and that is about the event
    loop rather than about laziness.** aiosqlite binds a connection to the loop
    that created it, and `create_app` is called *before* uvicorn's loop exists
    -- the same constraint that makes `Application.start()` a separate step
    from building it. Every other store here solves that by being started from
    the lifespan; this one is reached only from request handlers, so opening at
    the first of them lands on the right loop with no lifespan hook to forget.
    What it costs: the first settings request pays the `CREATE TABLE` and the
    schema reconciliation. What it buys: there is no state in which this object
    exists and answers `RuntimeError`, which is the failure mode a started/not
    started store has.
    """

    def __init__(
        self, db_path: str, tracer=None, revision: SettingsRevision | None = None
    ) -> None:
        self._db_path = db_path
        self._tracer = tracer
        self._connection: aiosqlite.Connection | None = None
        self._rows: ReadModelRepository | None = None
        self._opening = asyncio.Lock()
        #: Bumped by `put` and `clear`, read by `EffectiveSettings` to decide
        #: whether its cached bundle is still current. It lives here rather
        #: than at the route because this class is the single production
        #: writer for this table: a second write path added tomorrow -- a CLI
        #: import, a bulk endpoint -- invalidates the cache without knowing
        #: the cache exists. `None` builds its own, so a store constructed by
        #: a test is not obliged to care.
        self._revision = revision if revision is not None else SettingsRevision()

    @classmethod
    async def open(
        cls, db_path: str, tracer=None, revision: SettingsRevision | None = None
    ) -> "SettingsStore":
        """An already-opened store, for a caller that has a loop and wants the
        table to exist now -- the tests, mainly."""
        store = cls(db_path, tracer, revision)
        await store._ensure()
        return store

    async def _ensure(self) -> ReadModelRepository:
        """The repository, opening the connection once.

        Locked because two settings requests can arrive together on the first
        page load -- the schema read and the resolved read are two calls -- and
        two concurrent `CREATE TABLE`/`ALTER` runs against one file is a race
        with no symptom until the day it has one.
        """
        if self._rows is not None:
            return self._rows
        async with self._opening:
            if self._rows is not None:
                return self._rows
            connection = await aiosqlite.connect(self._db_path)
            await apply_schema(connection, SettingOverrideRow)
            # `apply_schema` reconciles columns, not indexes -- the same note
            # `EntityDefinitionStore.open` carries. Every read here filters on
            # the pair, and the settings page issues one query per scope in the
            # chain, so without this each page load scans every tenant's rows.
            await connection.execute(
                f"CREATE INDEX IF NOT EXISTS idx_setting_overrides_scope "
                f"ON {SettingOverrideRow.table_name()}(scope, scope_id)"
            )
            await connection.commit()
            self._connection = connection
            self._rows = SQLiteReadModelRepository(
                connection, SettingOverrideRow, self._tracer
            )
            return self._rows

    async def overrides(self, refs: Iterable[ScopeRef]) -> list[Override]:
        """Every override held by any of these scopes, in no particular order.

        Order is the resolver's business and this returns a flat list on
        purpose: a store that returned them "in resolution order" would be a
        second implementation of the walk, free to disagree with the one in
        `SettingsResolver` -- and a disagreement there is invisible, because
        both orders produce a plausible value.
        """
        rows_repo = await self._ensure()
        found: list[Override] = []
        for ref in refs:
            rows = await rows_repo.find(
                Query(
                    filters=[
                        Filter.eq("scope", ref.scope.value),
                        Filter.eq("scope_id", ref.scope_id),
                    ]
                )
            )
            found.extend(
                Override(
                    scope=Scope(row.scope),
                    scope_id=row.scope_id,
                    key=row.setting_key,
                    value=row.value,
                    updated_at=row.updated_at.isoformat(),
                )
                for row in rows
            )
        return found

    async def put(self, ref: ScopeRef, key: str, value: str) -> None:
        rows = await self._ensure()
        await rows.save(
            SettingOverrideRow(
                id=SettingOverrideRow.row_id(ref.scope, ref.scope_id, key),
                scope=ref.scope.value,
                scope_id=ref.scope_id,
                setting_key=key,
                value=value,
                updated_at=datetime.now(UTC),
            )
        )
        self._revision.bump()

    async def clear(self, ref: ScopeRef, key: str) -> bool:
        """Remove an override. False means there was nothing to remove.

        The boolean is what lets the route answer 404 for "clear something that
        was never set" instead of 204 -- clearing an unset key is almost always
        a typo in the key, and a silent success is how a typo survives.
        """
        rows = await self._ensure()
        row_id = SettingOverrideRow.row_id(ref.scope, ref.scope_id, key)
        if await rows.get(row_id) is None:
            return False
        await rows.delete(row_id)
        self._revision.bump()
        return True

    async def close(self) -> None:
        if self._connection is not None:
            await self._connection.close()
            self._connection = None
            self._rows = None
