"""Domain read model facade.

Re-exports all read model rows, stores, projections, runners, namespaces,
and helper functions across domain submodules.
"""

from __future__ import annotations

from research_team.infrastructure.persistence.art_read_models import (
    ArtRow,
    ArtStore,
    CandidateArtRow,
    CandidateArtStore,
)
from research_team.infrastructure.persistence.authoring_read_models import (
    AuthoringRunProjection,
    AuthoringRunRow,
    AuthoringRunRunner,
    AuthoringRunStore,
)
from research_team.infrastructure.persistence.corpus_read_models import (
    CORPUS_NAMESPACE,
    CorpusDocumentRow,
    CorpusMediaRow,
    CorpusProjection,
    CorpusRunner,
    CorpusStore,
    _decode_degradations,
    _degradations_of,
    to_record,
)
from research_team.infrastructure.persistence.course_read_models import (
    CatalogFeatureProjection,
    CatalogFeatureRow,
    CatalogFeatureStore,
    CourseBlurbRow,
    CourseBlurbStore,
    CourseOutlineRow,
    CourseOutlineStore,
    CourseProjection,
    CourseRow,
    CourseStore,
)
from research_team.infrastructure.persistence.dialogue_read_models import (
    ASK_NAMESPACE,
    SOCRATIC_NAMESPACE,
    AskConversationProjection,
    AskConversationRow,
    AskConversationRunner,
    AskConversationStore,
    AskTurnRow,
    SocraticDialogueProjection,
    SocraticDialogueRow,
    SocraticDialogueRunner,
    SocraticDialogueStore,
    SocraticTurnRow,
)
from research_team.infrastructure.persistence.media_read_models import (
    MEDIA_PROPOSAL_NAMESPACE,
    MediaIgnoredAssetRow,
    MediaIgnoredHostRow,
    MediaNeedRow,
    MediaProposalProjection,
    MediaProposalRow,
    MediaProposalRunner,
    MediaProposalStore,
)
from research_team.infrastructure.persistence.ontology_read_models import (
    DEFINITION_NAMESPACE,
    ONTOLOGY_NAMESPACE,
    EntityDefinitionProjection,
    EntityDefinitionRow,
    EntityDefinitionRunner,
    EntityDefinitionStore,
    OntologyClassRow,
    OntologyExaminedRow,
    OntologyMembershipRow,
    OntologyProjection,
    OntologyRunner,
    OntologyStore,
)
from research_team.infrastructure.persistence.session_read_models import (
    SessionSummaryProjection,
    SessionSummaryRow,
    SessionSummaryRunner,
    SessionSummaryStore,
    to_summary,
)
from research_team.infrastructure.persistence.store_base import (
    CATALOG_NAMESPACE,
    LOCAL_RETRY_POLICY,
    BaseProjectionRunner,
    BaseReadModelStore,
    apply_schema,
    model_schema,
    open_readmodel_connection,
)

__all__ = [
    "ASK_NAMESPACE",
    "CATALOG_NAMESPACE",
    "CORPUS_NAMESPACE",
    "DEFINITION_NAMESPACE",
    "LOCAL_RETRY_POLICY",
    "MEDIA_PROPOSAL_NAMESPACE",
    "ONTOLOGY_NAMESPACE",
    "SOCRATIC_NAMESPACE",
    "ArtRow",
    "ArtStore",
    "AskConversationProjection",
    "AskConversationRow",
    "AskConversationRunner",
    "AskConversationStore",
    "AskTurnRow",
    "AuthoringRunProjection",
    "AuthoringRunRow",
    "AuthoringRunRunner",
    "AuthoringRunStore",
    "BaseProjectionRunner",
    "BaseReadModelStore",
    "CandidateArtRow",
    "CandidateArtStore",
    "CatalogFeatureProjection",
    "CatalogFeatureRow",
    "CatalogFeatureStore",
    "CorpusDocumentRow",
    "CorpusMediaRow",
    "CorpusProjection",
    "CorpusRunner",
    "CorpusStore",
    "CourseBlurbRow",
    "CourseBlurbStore",
    "CourseOutlineRow",
    "CourseOutlineStore",
    "CourseProjection",
    "CourseRow",
    "CourseStore",
    "EntityDefinitionProjection",
    "EntityDefinitionRow",
    "EntityDefinitionRunner",
    "EntityDefinitionStore",
    "MediaIgnoredAssetRow",
    "MediaIgnoredHostRow",
    "MediaNeedRow",
    "MediaProposalProjection",
    "MediaProposalRow",
    "MediaProposalRunner",
    "MediaProposalStore",
    "OntologyClassRow",
    "OntologyExaminedRow",
    "OntologyMembershipRow",
    "OntologyProjection",
    "OntologyRunner",
    "OntologyStore",
    "SessionSummaryProjection",
    "SessionSummaryRow",
    "SessionSummaryRunner",
    "SessionSummaryStore",
    "SocraticDialogueProjection",
    "SocraticDialogueRow",
    "SocraticDialogueRunner",
    "SocraticDialogueStore",
    "SocraticTurnRow",
    "_decode_degradations",
    "_degradations_of",
    "apply_schema",
    "model_schema",
    "open_readmodel_connection",
    "to_record",
    "to_summary",
]
